# 行列演算の基礎

## (X^t X)^-1 X^t y

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [1]:
import numpy as np

In [5]:
# ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [6]:
# 行列の定義
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [7]:
# 転置
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [9]:
# 逆行列
#linear algebra : 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [12]:
#　行列積
XX_inv = np.dot(X,X_inv)
print(XX_inv)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# よくある間違い

In [25]:
x_mis =np.array ([1,2,3])  #[[]]二重カッコで転置可能
x_mis.T

array([1, 2, 3])

In [26]:
x_mis =np.array ([[1,2,3]]) 
x_mis.T

array([[1],
       [2],
       [3]])

## Numpyでよく使う処理

In [33]:
X = np.array([
    [1,2,3],
    [4,5,6]
])
print(X)

[[1 2 3]
 [4 5 6]]


In [34]:
X.shape

(2, 3)

In [39]:
row,col = X.shape

In [40]:
row

2

In [41]:
col

3

In [48]:
for x_mis in X:
    print(x_mis)
    print('- -')

[1 2 3]
- -
[4 5 6]
- -


# 演習問題

$ \boldsymbol{X} = \begin{bmatrix}
1&2&3 \\
1&2&5 \\
1&3&4 \\
1&5&9 \\
\end{bmatrix}
,\ \boldsymbol{y} = \begin{bmatrix}
1\\
5\\
6\\
8\\
\end{bmatrix}
$ のとき、

$\boldsymbol{w} =(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$  

- Step1: $\boldsymbol{X}^{T}\boldsymbol{X}$
- Step2: $(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$
- Step3: $\boldsymbol{X}^{T}\boldsymbol{y}$  
- Step4: $\boldsymbol{w} =(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$  

In [87]:
# Xの定義
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9],
])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [88]:
# yの定義
y = np.array([
    [1],
    [5],
    [6],
    [8],
])
print(y)

[[1]
 [5]
 [6]
 [8]]


In [89]:
# Step1
XtX = np.dot(X.T,X)
print(XtX)


[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


In [90]:
# Step2
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


In [93]:
# Step3
Xty = np.dot(X.T,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


In [96]:
# Step4
w = np.dot(XtX_inv,Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learn で実装

In [98]:
import sklearn   #Scikit-learn:ライブラリ

In [100]:
#　重回帰分析
from sklearn.linear_model import LinearRegression

In [109]:
# モデルの宣言
model = LinearRegression(fit_intercept=False)

In [110]:
# モデルの学習　←　パラメータの調整
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)

In [114]:
# 調整後のパラメータ
model.coef_      #coefficent:　係数(偏回帰)
print(model.coef_ )

[[-0.14285714  0.71428571  0.57142857]]


In [118]:
model.intercept_  #intercept: 切片

0.0

In [119]:
# 予測精度　←　決定係数
model.score(X,y)

0.6923076923076924

In [126]:
# 予測値(クエリ)の計算
x =np.array([[1,2,3]])

In [127]:
y_pred = model.predict(x)
print(y_pred) 

[[3.]]
